version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - USE_REDIS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"